- op: add
  path: /spec/values/extraObjects
  value:
    - apiVersion: argoproj.io/v1alpha1
      kind: EventBus
      metadata:
        name: default
        annotations:
          "helm.sh/hook": post-install,post-upgrade
      spec:
        nats:
          native:
            replicas: 3
            auth: token
            persistence:
              storageClassName: standard
              accessMode: ReadWriteOnce
              volumeSize: 10Gi
