apiVersion: apps/v1
kind: Deployment
metadata:
  name: milo-controller-manager
spec:
  template:
    spec:
      containers:
      - name: milo-controller-manager
        env:
          # Point to the kubeconfig for Milo API server
          - name: KUBECONFIG
            value: "/etc/kubernetes/config/kubeconfig"
          # Use the API server TLS cert for webhook temporarily
          - name: TLS_CERT_FILE
            value: "/etc/kubernetes/pki/webhook/tls.crt"
          - name: TLS_PRIVATE_KEY_FILE
            value: "/etc/kubernetes/pki/webhook/tls.key"
        volumeMounts:
          - name: kubeconfig
            mountPath: /etc/kubernetes/config
            readOnly: true
          - name: webhook-certs
            mountPath: /etc/kubernetes/pki/webhook
            readOnly: true
      volumes:
        - name: kubeconfig
          secret:
            secretName: milo-controller-manager-kubeconfig
        - name: webhook-certs
          secret:
            secretName: milo-apiserver-tls
