apiVersion: apps/v1
kind: Deployment
metadata:
  name: milo-apiserver
spec:
  template:
    spec:
      containers:
      - name: milo-apiserver
        imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milo-controller-manager
spec:
  template:
    spec:
      containers:
      - name: milo-controller-manager
        imagePullPolicy: IfNotPresent
