kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: "notification.miloapis.com"
        kind: "Contact"
        version: "v1alpha1"
      metricNamePrefix: milo_contacts
      commonLabels:
        component: notification
        resource_type: contact
      labelsFromPath:
        subject_kind: [spec, subject, kind]
        subject_name: [spec, subject, name]
        email: [spec, email]
      metrics:
        - name: "info"
          help: "Information about contacts"
          each:
            type: Info
            info:
              labelsFromPath:
                uid: [metadata, uid]
                name: [metadata, name]
                namespace: [metadata, namespace]

        - name: "status_condition"
          help: "Status conditions for contacts"
          each:
            type: Info
            info:
              path: [status, conditions]
              labelsFromPath:
                type: [type]
                status: [status]

        - name: "created_timestamp"
          help: "Timestamp when the contact was created"
          each:
            type: Gauge
            gauge:
              path: [metadata, creationTimestamp]

        - name: "current_generation"
          help: "The current generation for the contact"
          each:
            type: Gauge
            gauge:
              path: [metadata, generation]
