kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: "notification.miloapis.com"
        kind: "ContactGroup"
        version: "v1alpha1"
      metricNamePrefix: milo_contact_groups
      commonLabels:
        component: notification
        resource_type: contact_group
      metrics:
        - name: "info"
          help: "Information about contact groups"
          each:
            type: Info
            info:
              labelsFromPath:
                uid: [metadata, uid]
                name: [metadata, name]
                namespace: [metadata, namespace]

        - name: "status_condition"
          help: "Status conditions for contact groups"
          each:
            type: Info
            info:
              path: [status, conditions]
              labelsFromPath:
                type: [type]
                status: [status]

        - name: "created_timestamp"
          help: "Timestamp when the contact group was created"
          each:
            type: Gauge
            gauge:
              path: [metadata, creationTimestamp]

        - name: "current_generation"
          help: "The current generation for the contact group"
          each:
            type: Gauge
            gauge:
              path: [metadata, generation]
