kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: "notification.miloapis.com"
        kind: "EmailTemplate"
        version: "v1alpha1"
      metricNamePrefix: milo_email_templates
      commonLabels:
        component: notification
        resource_type: email_template
      metrics:
        - name: "info"
          help: "Information about email templates"
          each:
            type: Info
            info:
              labelsFromPath:
                uid: [metadata, uid]
                name: [metadata, name]

        - name: "status_condition"
          help: "Status conditions for email templates"
          each:
            type: Info
            info:
              path: [status, conditions]
              labelsFromPath:
                type: [type]
                status: [status]

        - name: "created_timestamp"
          help: "Timestamp when the email template was created"
          each:
            type: Gauge
            gauge:
              path: [metadata, creationTimestamp]

        - name: "observed_generation"
          help: "The observed generation for the email template"
          each:
            type: Gauge
            gauge:
              path: [status, observedGeneration]
              nilIsZero: true

        - name: "current_generation"
          help: "The current generation for the email template"
          each:
            type: Gauge
            gauge:
              path: [metadata, generation]
