apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: milo-system
configMapGenerator:
  - name: milo-infrastructure-resource-metrics
    files:
    - project_control_planes.yaml
    options:
      labels:
        telemetry.datumapis.com/core-resource-metrics-config: "true"
