# This policy is used to create a kubeconfig for the project control plane
# whenever it discovers a new secret that contains a certificate used to
# authenticate with a project control plane.
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-project-controlplane-kubeconfig
spec:
  rules:
  - name: generate-kubeconfig
    match:
      all:
      - resources:
          kinds:
          - Secret
          selector:
            matchLabels:
              resourcemanager.miloapis.com/project-control-plane-kubeconfig-certificate: "true"
    generate:
      generateExisting: true
      orphanDownstreamOnPolicyDelete: true
      apiVersion: v1
      kind: Secret
      name: "{{ request.object.metadata.name }}-kubeconfig"
      namespace: "{{request.object.metadata.namespace}}"
      synchronize: true
      data:
        metadata:
          labels:
            resourcemanager.miloapis.com/project-name: "{{ lookup(request.object.metadata.labels, 'resourcemanager.miloapis.com/project-name') }}"
            resourcemanager.miloapis.com/project-controlplane-kubeconfig: "true"
        stringData:
          kubeconfig: |
            apiVersion: v1
            kind: Config
            clusters:
            - name: project-controlplane
              cluster:
                certificate-authority-data: "{{ lookup(request.object.data, 'ca.crt') }}"
                server: https://milo-apiserver.{{request.object.metadata.namespace}}.svc.cluster.local:6443
            users:
            - name: project-controlplane-user
              user:
                client-certificate-data: "{{ lookup(request.object.data, 'tls.crt') }}"
                client-key-data: "{{ lookup(request.object.data, 'tls.key') }}"
            contexts:
            - name: project-controlplane
              context:
                cluster: project-controlplane
                user: project-controlplane-user
            current-context: project-controlplane
  - name: generate-core-control-plane-kubeconfig
    match:
      all:
      - resources:
          kinds:
          - Secret
          selector:
            matchLabels:
              resourcemanager.miloapis.com/core-control-plane-kubeconfig-certificate: "true"
    generate:
      generateExisting: true
      apiVersion: v1
      kind: Secret
      name: "{{ request.object.metadata.name }}-kubeconfig"
      namespace: "{{request.object.metadata.namespace}}"
      synchronize: true
      data:
        metadata:
          labels:
            resourcemanager.miloapis.com/core-control-plane-kubeconfig: "true"
        stringData:
          value: |
            apiVersion: v1
            kind: Config
            clusters:
            - name: core-control-plane
              cluster:
                certificate-authority-data: "{{ lookup(request.object.data, 'ca.crt') }}"
                server: https://milo-apiserver.{{request.object.metadata.namespace}}.svc.cluster.local:6443
            users:
            - name: core-control-plane-user
              user:
                client-certificate-data: "{{ lookup(request.object.data, 'tls.crt') }}"
                client-key-data: "{{ lookup(request.object.data, 'tls.key') }}"
            contexts:
            - name: core-control-plane
              context:
                cluster: core-control-plane
                user: core-control-plane-user
            current-context: core-control-plane
