serviceId: resourcemanager.datumapis.com
name: services/resourcemanager.datumapis.com
displayName: Datum Resource Manager Service
spec:
  resources:
  - type: resourcemanager.datumapis.com/Organization
    plural: organizations
    singular: organization
    permissions:
    - list
    - get
    - create
    - update
    - delete
    - search
    resourceNamePatterns:
    - "organizations/{organization}"
  - type: resourcemanager.datumapis.com/Invitation
    plural: invitations
    singular: invitation
    permissions:
    - list
    - get
    - create
    - update
    - delete
    - accept
    resourceNamePatterns:
    - "organizations/{organization}/invitations/{invitation}"
    parentResources:
    - resourcemanager.datumapis.com/Organization