apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: iam.miloapis.com-platformaccessrejection
spec:
  serviceRef:
    name: "iam.miloapis.com"
  kind: PlatformAccessRejection
  plural: platformaccessrejections
  singular: platformaccessrejection
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
