apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: iam.miloapis.com-platformaccessapproval
spec:
  serviceRef:
    name: "iam.miloapis.com"
  kind: PlatformAccessApproval
  plural: platformaccessapprovals
  singular: platformaccessapproval
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
