# project-alpha.yaml
apiVersion: resourcemanager.miloapis.com/v1alpha1
kind: Project
metadata:
  name: alpha
spec:
  ownerRef:
    kind: Organization
    name: test@example.com
---
apiVersion: resourcemanager.miloapis.com/v1alpha1
kind: Project
metadata:
  name: beta
spec:
  ownerRef:
    kind: Organization
    name: test@example.com
---
apiVersion: resourcemanager.miloapis.com/v1alpha1
kind: Project
metadata:
  name: gamma
spec:
  ownerRef:
    kind: Organization
    name: test@example.com