apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-events
spec:
  interval: 5m
  chart:
    spec:
      chart: argo-events
      version: "2.4.16"
      sourceRef:
        kind: HelmRepository
        name: argo
  releaseName: argo-events
  install:
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  values:
    # Deploy in namespaced mode - only watch resources in milo-system namespace
    # This creates appropriate RBAC (Roles/RoleBindings instead of ClusterRoles)
    # and limits the controller's scope to a single namespace
    singleNamespace: true

    # Namespace where EventSources and Sensors will be deployed
    # Must match the namespace of this HelmRelease
    namespace: milo-system

    controller:
      serviceAccount:
        create: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

    webhook:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
