//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Address) DeepCopyInto(out *Address) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Address.
func (in *Address) DeepCopy() *Address {
	if in == nil {
		return nil
	}
	out := new(Address)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaxIdReference) DeepCopyInto(out *TaxIdReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaxIdReference.
func (in *TaxIdReference) DeepCopy() *TaxIdReference {
	if in == nil {
		return nil
	}
	out := new(TaxIdReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaxInfo) DeepCopyInto(out *TaxInfo) {
	*out = *in
	out.TaxIdRef = in.TaxIdRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaxInfo.
func (in *TaxInfo) DeepCopy() *TaxInfo {
	if in == nil {
		return nil
	}
	out := new(TaxInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Vendor) DeepCopyInto(out *Vendor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Vendor.
func (in *Vendor) DeepCopy() *Vendor {
	if in == nil {
		return nil
	}
	out := new(Vendor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Vendor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VendorList) DeepCopyInto(out *VendorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Vendor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VendorList.
func (in *VendorList) DeepCopy() *VendorList {
	if in == nil {
		return nil
	}
	out := new(VendorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VendorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VendorReference) DeepCopyInto(out *VendorReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VendorReference.
func (in *VendorReference) DeepCopy() *VendorReference {
	if in == nil {
		return nil
	}
	out := new(VendorReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VendorSpec) DeepCopyInto(out *VendorSpec) {
	*out = *in
	out.BillingAddress = in.BillingAddress
	if in.MailingAddress != nil {
		in, out := &in.MailingAddress, &out.MailingAddress
		*out = new(Address)
		**out = **in
	}
	out.TaxInfo = in.TaxInfo
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VendorSpec.
func (in *VendorSpec) DeepCopy() *VendorSpec {
	if in == nil {
		return nil
	}
	out := new(VendorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VendorStatus) DeepCopyInto(out *VendorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastVerifiedAt != nil {
		in, out := &in.LastVerifiedAt, &out.LastVerifiedAt
		*out = (*in).DeepCopy()
	}
	if in.ActivatedAt != nil {
		in, out := &in.ActivatedAt, &out.ActivatedAt
		*out = (*in).DeepCopy()
	}
	if in.RejectedAt != nil {
		in, out := &in.RejectedAt, &out.RejectedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VendorStatus.
func (in *VendorStatus) DeepCopy() *VendorStatus {
	if in == nil {
		return nil
	}
	out := new(VendorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VendorStatusSummary) DeepCopyInto(out *VendorStatusSummary) {
	*out = *in
	if in.LastVerifiedAt != nil {
		in, out := &in.LastVerifiedAt, &out.LastVerifiedAt
		*out = (*in).DeepCopy()
	}
	if in.ActivatedAt != nil {
		in, out := &in.ActivatedAt, &out.ActivatedAt
		*out = (*in).DeepCopy()
	}
	if in.RejectedAt != nil {
		in, out := &in.RejectedAt, &out.RejectedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VendorStatusSummary.
func (in *VendorStatusSummary) DeepCopy() *VendorStatusSummary {
	if in == nil {
		return nil
	}
	out := new(VendorStatusSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VendorTypeDefinition) DeepCopyInto(out *VendorTypeDefinition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VendorTypeDefinition.
func (in *VendorTypeDefinition) DeepCopy() *VendorTypeDefinition {
	if in == nil {
		return nil
	}
	out := new(VendorTypeDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VendorTypeDefinition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VendorTypeDefinitionList) DeepCopyInto(out *VendorTypeDefinitionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VendorTypeDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VendorTypeDefinitionList.
func (in *VendorTypeDefinitionList) DeepCopy() *VendorTypeDefinitionList {
	if in == nil {
		return nil
	}
	out := new(VendorTypeDefinitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VendorTypeDefinitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VendorTypeDefinitionSpec) DeepCopyInto(out *VendorTypeDefinitionSpec) {
	*out = *in
	if in.ValidCountries != nil {
		in, out := &in.ValidCountries, &out.ValidCountries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequiredTaxDocuments != nil {
		in, out := &in.RequiredTaxDocuments, &out.RequiredTaxDocuments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VendorTypeDefinitionSpec.
func (in *VendorTypeDefinitionSpec) DeepCopy() *VendorTypeDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(VendorTypeDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VendorTypeDefinitionStatus) DeepCopyInto(out *VendorTypeDefinitionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastUsed != nil {
		in, out := &in.LastUsed, &out.LastUsed
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VendorTypeDefinitionStatus.
func (in *VendorTypeDefinitionStatus) DeepCopy() *VendorTypeDefinitionStatus {
	if in == nil {
		return nil
	}
	out := new(VendorTypeDefinitionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VendorVerification) DeepCopyInto(out *VendorVerification) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VendorVerification.
func (in *VendorVerification) DeepCopy() *VendorVerification {
	if in == nil {
		return nil
	}
	out := new(VendorVerification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VendorVerification) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VendorVerificationList) DeepCopyInto(out *VendorVerificationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VendorVerification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VendorVerificationList.
func (in *VendorVerificationList) DeepCopy() *VendorVerificationList {
	if in == nil {
		return nil
	}
	out := new(VendorVerificationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VendorVerificationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VendorVerificationSpec) DeepCopyInto(out *VendorVerificationSpec) {
	*out = *in
	out.VendorRef = in.VendorRef
	if in.Documents != nil {
		in, out := &in.Documents, &out.Documents
		*out = make([]VerificationDocument, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VerifierRef != nil {
		in, out := &in.VerifierRef, &out.VerifierRef
		*out = new(VerifierReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ExpirationDate != nil {
		in, out := &in.ExpirationDate, &out.ExpirationDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VendorVerificationSpec.
func (in *VendorVerificationSpec) DeepCopy() *VendorVerificationSpec {
	if in == nil {
		return nil
	}
	out := new(VendorVerificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VendorVerificationStatus) DeepCopyInto(out *VendorVerificationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.LastUpdatedAt != nil {
		in, out := &in.LastUpdatedAt, &out.LastUpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VendorVerificationStatus.
func (in *VendorVerificationStatus) DeepCopy() *VendorVerificationStatus {
	if in == nil {
		return nil
	}
	out := new(VendorVerificationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerificationDocument) DeepCopyInto(out *VerificationDocument) {
	*out = *in
	if in.ExpirationDate != nil {
		in, out := &in.ExpirationDate, &out.ExpirationDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerificationDocument.
func (in *VerificationDocument) DeepCopy() *VerificationDocument {
	if in == nil {
		return nil
	}
	out := new(VerificationDocument)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerificationSummary) DeepCopyInto(out *VerificationSummary) {
	*out = *in
	if in.VerificationTypes != nil {
		in, out := &in.VerificationTypes, &out.VerificationTypes
		*out = make(map[VerificationType]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerificationSummary.
func (in *VerificationSummary) DeepCopy() *VerificationSummary {
	if in == nil {
		return nil
	}
	out := new(VerificationSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifierReference) DeepCopyInto(out *VerifierReference) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifierReference.
func (in *VerifierReference) DeepCopy() *VerifierReference {
	if in == nil {
		return nil
	}
	out := new(VerifierReference)
	in.DeepCopyInto(out)
	return out
}
