# authentication-webhook-kubeconfig.yaml
#
# This kubeconfig tells the Milo API server where to send TokenReview requests
# for bearer-token authentication. It points at the User Authentication webhook
# served by `zitadel-auth-provider`.
#
# NOTE: The configuration below is safe for local development only. It skips
# TLS verification because the webhook is usually started with the `--insecure`
# flag when running on localhost.  For any non-dev environment, replace
# `insecure-skip-tls-verify: true` with a `certificate-authority:` field that
# references the CA bundle which signed the webhook’s TLS certificate.
#
apiVersion: v1
kind: Config

clusters:
- name: milo-authentication-webhook
  cluster:
    # Where the webhook server is reachable. When running with Docker Desktop or
    # through the devcontainer this resolves to the host machine.
    server: https://localhost:8443/authenticate

    # Dev-only: do NOT use in production.
    insecure-skip-tls-verify: true
    # certificate-authority: /path/to/ca.pem  # ← use instead of insecure-skip in prod

users:
- name: milo-apiserver
  user: {}

contexts:
- name: webhook
  context:
    cluster: milo-authentication-webhook
    user: milo-apiserver

current-context: webhook
