apiVersion: iam.miloapis.com/v1alpha1
kind: UserPreference
metadata:
  name: userpreference-sample
spec:
  userRef:
    name: user-sample
  theme: "dark"
  displayName: my display name
  title: my title