apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: notification.miloapis.com-contactgroup
spec:
  serviceRef:
    name: "notification.miloapis.com"
  kind: ContactGroup
  plural: contactgroups
  singular: contactgroup
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
