apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: notification.miloapis.com-contactgroupmembershipremoval
spec:
  serviceRef:
    name: "notification.miloapis.com"
  kind: ContactGroupMembershipRemoval
  plural: contactgroupmembershipremovals
  singular: contactgroupmembershipremoval
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
