apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: notification.miloapis.com-email
spec:
  serviceRef:
    name: "notification.miloapis.com"
  kind: Email
  plural: emails
  singular: email
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
