apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: notification.miloapis.com-emailbroadcast
spec:
  serviceRef:
    name: "notification.miloapis.com"
  kind: EmailBroadcast
  plural: emailbroadcasts
  singular: emailbroadcast
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch