apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: milo-apiserver-tracing-config
    files:
      - tracing-config.yaml

patches:
  # Enable tracing in API server deployment
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: milo-apiserver
      spec:
        template:
          spec:
            containers:
            - name: milo-apiserver
              env:
              - name: TRACING_CONFIG_FILE
                value: "/etc/kubernetes/tracing/tracing-config.yaml"
              volumeMounts:
              - name: tracing-config
                mountPath: /etc/kubernetes/tracing
                readOnly: true
            volumes:
            - name: tracing-config
              configMap:
                name: milo-apiserver-tracing-config
    target:
      kind: Deployment
      name: milo-apiserver