apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: milo-system
configMapGenerator:
  - name: milo-resource-metrics
    files:
    - projects.yaml
    - organizations.yaml
    - organization_memberships.yaml 
    options:
      labels:
        telemetry.datumapis.com/core-resource-metrics-config: "true"
