kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: "resourcemanager.miloapis.com"
        kind: "OrganizationMembership"
        version: "v1alpha1"
      labelsFromPath:
        name: [metadata, name]
        namespace: [metadata, namespace]
      metricNamePrefix: milo_organization_memberships
      metrics:
        - name: "info"
          each:
            type: Info
            info:
              labelsFromPath:
                organization_type: ["spec", "type"]
                uid: [metadata, uid]
        - name: "created_timestamp"
          each:
            type: Gauge
            gauge:
              path: [metadata, creationTimestamp]
        - name: "status_condition"
          each:
            type: Gauge
            gauge:
              path: [status, conditions]
              labelsFromPath:
                type: ["type"]
                reason: ["reason"]
              valueFrom: ["status"]
        - name: "status_condition_last_transition_time"
          each:
            type: Gauge
            gauge:
              path: [status, conditions]
              labelsFromPath:
                type: ["type"]
                reason: ["reason"]
                status: ["status"]
              valueFrom: ["lastTransitionTime"]
