kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: "resourcemanager.miloapis.com"
        kind: "Project"
        version: "v1alpha1"
      metricNamePrefix: milo_projects
      commonLabels:
        component: resource_manager
        resource_type: project
      labelsFromPath:
        owner_kind: [spec, ownerRef, kind]
        owner_name: [spec, ownerRef, name]
      metrics:
        - name: "info"
          help: "Information about projects"
          each:
            type: Info
            info:
              labelsFromPath:
                uid: [metadata, uid]
                name: [metadata, name]
                namespace: [metadata, namespace]

        - name: "status_condition"
          help: "Status conditions for projects"
          each:
            type: Info
            info:
              path: [status, conditions]
              labelsFromPath:
                type: [type]
                status: [status]

        - name: "created_timestamp"
          help: "Timestamp when the project was created"
          each:
            type: Gauge
            gauge:
              path: [metadata, creationTimestamp]

        - name: "observed_generation"
          help: "The observed generation for the project"
          each:
            type: Gauge
            gauge:
              path: [status, observedGeneration]
              nilIsZero: true

        - name: "current_generation"
          help: "The current generation for the project"
          each:
            type: Gauge
            gauge:
              path: [metadata, generation]
