kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: quota.miloapis.com
        version: "*"
        kind: AllowanceBucket
      metricNamePrefix: milo_quota_bucket
      commonLabels:
        component: quota_system
        resource_type: bucket
      labelsFromPath:
        consumer_api_group: [spec, consumerRef, apiGroup]
        consumer_kind: [spec, consumerRef, kind]
        consumer_name: [spec, consumerRef, name]
        resource_type: [spec, resourceType]
      metrics:
        - name: "info"
          help: "Information about quota allowance buckets"
          each:
            type: Info
            info:
              labelsFromPath:
                uid: [metadata, uid]
                name: [metadata, name]
                namespace: [metadata, namespace]

        - name: "limit"
          help: "Total quota limit from all contributing grants"
          each:
            type: Gauge
            gauge:
              path: [status, limit]

        - name: "allocated"
          help: "Total quota currently consumed by granted claims"
          each:
            type: Gauge
            gauge:
              path: [status, allocated]

        - name: "available"
          help: "Available quota capacity (limit - allocated)"
          each:
            type: Gauge
            gauge:
              path: [status, available]

        - name: "claim_count"
          help: "Number of claims consuming quota from this bucket"
          each:
            type: Gauge
            gauge:
              path: [status, claimCount]

        - name: "grant_count"
          help: "Number of grants contributing to this bucket"
          each:
            type: Gauge
            gauge:
              path: [status, grantCount]

        - name: "last_reconciliation_timestamp"
          help: "Timestamp of last bucket reconciliation"
          each:
            type: Gauge
            gauge:
              path: [status, lastReconciliation]

        - name: "observed_generation"
          help: "The observed generation for the bucket"
          each:
            type: Gauge
            gauge:
              path: [status, observedGeneration]

        - name: "current_generation"
          help: "The current generation for the bucket"
          each:
            type: Gauge
            gauge:
              path: [metadata, generation]
