kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: quota.miloapis.com
        version: "*"
        kind: ClaimCreationPolicy
      metricNamePrefix: milo_quota_claim_policy
      commonLabels:
        component: quota_system
        resource_type: claim_policy
      labelsFromPath:
        target_api_version: [spec, trigger, resource, apiVersion]
        target_kind: [spec, trigger, resource, kind]
        enabled: [spec, enabled]
      metrics:
        - name: "info"
          help: "Information about quota claim creation policies"
          each:
            type: Info
            info:
              labelsFromPath:
                uid: [metadata, uid]
                name: [metadata, name]

        - name: "status_condition"
          help: "Status conditions for quota claim creation policies"
          each:
            type: Info
            info:
              path: [status, conditions]
              labelsFromPath:
                type: [type]
                status: [status]

        - name: "enabled"
          help: "Whether the policy is enabled (1 = enabled, 0 = disabled)"
          each:
            type: Gauge
            gauge:
              path: [spec, enabled]

        - name: "observed_generation"
          help: "The observed generation for the policy"
          each:
            type: Gauge
            gauge:
              path: [status, observedGeneration]
              nilIsZero: true

        - name: "current_generation"
          help: "The current generation for the policy"
          each:
            type: Gauge
            gauge:
              path: [metadata, generation]
