apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Kustomize component for quota system custom resource state metrics
# Creates ConfigMaps that the resource-metrics-collector sidecar will discover
# and merge into its kube-state-metrics configuration
configMapGenerator:
  - name: milo-quota-resourceregistrations-metrics
    options:
      labels:
        quota.miloapis.com/resource-type: resourceregistrations
    files:
      - config.yaml=resourceregistrations.yaml

  - name: milo-quota-resourcegrants-metrics
    options:
      labels:
        quota.miloapis.com/resource-type: resourcegrants
    files:
      - config.yaml=resourcegrants.yaml

  - name: milo-quota-resourceclaims-metrics
    options:
      labels:
        quota.miloapis.com/resource-type: resourceclaims
    files:
      - config.yaml=resourceclaims.yaml

  - name: milo-quota-allowancebuckets-metrics
    options:
      labels:
        quota.miloapis.com/resource-type: allowancebuckets
    files:
      - config.yaml=allowancebuckets.yaml

  - name: milo-quota-claimcreationpolicies-metrics
    options:
      labels:
        quota.miloapis.com/resource-type: claimcreationpolicies
    files:
      - config.yaml=claimcreationpolicies.yaml

  - name: milo-quota-grantcreationpolicies-metrics
    options:
      labels:
        quota.miloapis.com/resource-type: grantcreationpolicies
    files:
      - config.yaml=grantcreationpolicies.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: milo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: quota-metrics
    telemetry.datumapis.com/core-resource-metrics-config: "true"
