kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: quota.miloapis.com
        version: "*"
        kind: ResourceClaim
      metricNamePrefix: milo_quota_claim
      commonLabels:
        component: quota_system
        resource_type: claim
      labelsFromPath:
        consumer_api_group: [spec, consumerRef, apiGroup]
        consumer_kind: [spec, consumerRef, kind]
        consumer_name: [spec, consumerRef, name]
        triggering_resource_api_group: [spec, resourceRef, apiGroup]
        triggering_resource_kind: [spec, resourceRef, kind]
        triggering_resource_name: [spec, resourceRef, name]
        triggering_resource_namespace: [spec, resourceRef, namespace]
      metrics:
        - name: "info"
          help: "Information about quota resource claims"
          each:
            type: Info
            info:
              labelsFromPath:
                uid: [metadata, uid]
                name: [metadata, name]
                namespace: [metadata, namespace]

        - name: "status_condition"
          help: "Status conditions for quota resource claims"
          each:
            type: Info
            info:
              path: [status, conditions]
              labelsFromPath:
                type: [type]
                status: [status]

        - name: "observed_generation"
          help: "The observed generation for the claim"
          each:
            type: Gauge
            gauge:
              path: [status, observedGeneration]
              nilIsZero: true

        - name: "current_generation"
          help: "The current generation for the claim"
          each:
            type: Gauge
            gauge:
              path: [metadata, generation]