kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: quota.miloapis.com
        version: "*"
        kind: ResourceGrant
      metricNamePrefix: milo_quota_grant
      commonLabels:
        component: quota_system
        resource_type: grant
      labelsFromPath:
        consumer_api_group: [spec, consumerRef, apiGroup]
        consumer_kind: [spec, consumerRef, kind]
        consumer_name: [spec, consumerRef, name]
      metrics:
        - name: "info"
          help: "Information about quota resource grants"
          each:
            type: Info
            info:
              labelsFromPath:
                uid: [metadata, uid]
                name: [metadata, name]
                namespace: [metadata, namespace]

        - name: "status_condition"
          help: "Status conditions for quota resource grants"
          each:
            type: Info
            info:
              path: [status, conditions]
              labelsFromPath:
                type: [type]
                status: [status]

        - name: "observed_generation"
          help: "The observed generation for the grant"
          each:
            type: Gauge
            gauge:
              path: [status, observedGeneration]
              nilIsZero: true

        - name: "current_generation"
          help: "The current generation for the grant"
          each:
            type: Gauge
            gauge:
              path: [metadata, generation]