kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: quota.miloapis.com
        version: "*"
        kind: ResourceRegistration
      metricNamePrefix: milo_quota_registration
      commonLabels:
        component: quota_system
        resource_type: registration
      labelsFromPath:
        consumer_api_group: [spec, consumerTypeRef, apiGroup]
        consumer_kind: [spec, consumerTypeRef, kind]
        resource_type: [spec, resourceType]
        registration_type: [spec, type]
        base_unit: [spec, baseUnit]
        display_unit: [spec, displayUnit]
      metrics:
        - name: "info"
          help: "Information about quota resource registrations"
          each:
            type: Info
            info:
              labelsFromPath:
                uid: [metadata, uid]
                name: [metadata, name]
                description: [spec, description]
                unit_conversion_factor: [spec, unitConversionFactor]

        - name: "status_condition"
          help: "Status conditions for quota resource registrations"
          each:
            type: Info
            info:
              path: [status, conditions]
              labelsFromPath:
                type: [type]
                status: [status]

        - name: "observed_generation"
          help: "The observed generation for the registration"
          each:
            type: Gauge
            gauge:
              path: [status, observedGeneration]
              nilIsZero: true

        - name: "current_generation"
          help: "The current generation for the registration"
          each:
            type: Gauge
            gauge:
              path: [metadata, generation]