apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-state-metrics-crd-sidecar-script
data:
  compile.sh: |
    #!/bin/sh
    set -x

    SOURCE_DIR="/tmp"
    TARGET_FILE="/etc/config/crd-metrics-config.yaml"
    # This script will use a temporary file to only overwrite the target file once.
    TARGET_FILE_TMP="${TARGET_FILE}.tmp"
    # Create header
    cat << EOF > "${TARGET_FILE_TMP}"
    kind: CustomResourceStateMetrics
    spec:
      resources:
    EOF
    # Append custom resource config of all files but remove headers
    for f in $(ls -1 ${SOURCE_DIR}/*.yaml); do
      cat $f | grep -v -E -e '^(-|kind: CustomResourceStateMetrics|spec:| +resources:)' \
        >> "${TARGET_FILE_TMP}"
    done

    # Print diff if files differ
    if ! cmp -s "${TARGET_FILE_TMP}" "${TARGET_FILE}"; then
      echo "Changes detected:"
      diff "${TARGET_FILE}" "${TARGET_FILE_TMP}" || true
      mv "${TARGET_FILE_TMP}" "${TARGET_FILE}"
    else
      echo "No changes detected"
      rm "${TARGET_FILE_TMP}"
    fi
