apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: custom-resources-state-metrics
    app.kubernetes.io/version: 2.15.0
  name: custom-resources-state-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: custom-resources-state-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: custom-resources-state-metrics
        app.kubernetes.io/version: 2.15.0
    spec:
      automountServiceAccountToken: true
      volumes:
        - name: config-volume
          emptyDir: {}
        - name: compile-script
          configMap:
            name: kube-state-metrics-crd-sidecar-script
            defaultMode: 511
        - name: milo-kubeconfig
          configMap:
            name: milo-kubeconfig
            defaultMode: 0644
        - name: milo-certs
          csi:
            driver: csi.cert-manager.io
            readOnly: true
            volumeAttributes:
              csi.cert-manager.io/issuer-name: milo-ca-issuer
              csi.cert-manager.io/issuer-kind: Issuer
              csi.cert-manager.io/common-name: custom-resources-state-metrics
              csi.cert-manager.io/organizations: system:masters
              csi.cert-manager.io/duration: 24h
              csi.cert-manager.io/renew-before: 1h
              csi.cert-manager.io/fs-group: "65534"
      initContainers:
      - command:
        - /bin/sh
        - -c
        - |
          cat << EOF > "/etc/config/crd-metrics-config.yaml"
          kind: CustomResourceStateMetrics
          spec:
            resources: []
          EOF
        # This container initializes an empty configuration for kube-state-metrics
        # to have a smooth start.
        image: kiwigrid/k8s-sidecar:latest
        name: init-crd-config
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      containers:
        - name: sidecar
          image: kiwigrid/k8s-sidecar:latest
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
          - name: compile-script
            mountPath: /script
          - name: milo-kubeconfig
            mountPath: /etc/milo-kubeconfig
            readOnly: true
          - name: milo-certs
            mountPath: /var/run/secrets/milo-certs
            readOnly: true
          env:
          - name: KUBECONFIG
            value: /etc/milo-kubeconfig/kubeconfig
          - name: NAMESPACE
            value: ALL
          - name: LABEL
            value: "custom-resource-metrics-config"
          - name: LABEL_VALUE
            value: "true"
          - name: FOLDER
            value: /tmp/
          - name: RESOURCE
            value: configmap
          - name: SCRIPT
            value: /script/compile.sh
          - name: UNIQUE_FILENAMES
            value: "true"
        - name: custom-resources-state-metrics
          image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.15.0
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
          - name: milo-kubeconfig
            mountPath: /etc/milo-kubeconfig
            readOnly: true
          - name: milo-certs
            mountPath: /var/run/secrets/milo-certs
            readOnly: true
          env:
          - name: KUBECONFIG
            value: /etc/milo-kubeconfig/kubeconfig
          livenessProbe:
            httpGet:
              path: /livez
              port: http-metrics
            initialDelaySeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              name: http-metrics
            - containerPort: 8081
              name: telemetry
          readinessProbe:
            httpGet:
              path: /readyz
              port: telemetry
            initialDelaySeconds: 5
            timeoutSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
          args:
            - --kubeconfig=/etc/milo-kubeconfig/kubeconfig
            # - --use-apiserver-cache=true
            - --custom-resource-state-only=true
            - --custom-resource-state-config-file=/etc/config/crd-metrics-config.yaml

      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: custom-resources-state-metrics
