apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: custom-resources-state-metrics
    app.kubernetes.io/version: 2.15.0
  name: custom-resources-state-metrics
