apiVersion: v1
kind: Service
metadata:
  name: milo-controller-manager
  labels:
    app: milo-controller-manager
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: milo-controller-manager
  ports:
  - name: https
    port: 6443
    protocol: TCP
    targetPort: https
  - name: ctrl-mgr
    port: 9443
    protocol: TCP
    targetPort: ctrl-mgr
