apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --audit-policy-file=$(AUDIT_POLICY_FILE)
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --audit-webhook-initial-backoff=$(AUDIT_WEBHOOK_INITIAL_BACKOFF)
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --audit-webhook-config-file=$(AUDIT_WEBHOOK_CONFIG_FILE)
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --audit-webhook-mode=$(AUDIT_WEBHOOK_MODE)
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: AUDIT_POLICY_FILE
          value: "/etc/kubernetes/config/audit-policy-config.yaml"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: AUDIT_WEBHOOK_INITIAL_BACKOFF
          value: "10s"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: AUDIT_WEBHOOK_CONFIG_FILE
          value: "/etc/kubernetes/config/audit-webhook-config.yaml"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: AUDIT_WEBHOOK_MODE
          value: "batch"
    target:
      group: apps
      version: v1
      kind: Deployment
      name: milo-apiserver
