apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - audit-policy-configmap.yaml
  - audit-webhook-configmap.yaml

patches:
  # Add audit logging volume mounts using strategic merge
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: milo-apiserver
      spec:
        template:
          spec:
            containers:
            - name: milo-apiserver
              volumeMounts:
                - name: audit-policy-config
                  mountPath: /etc/kubernetes/config/audit-policy-config.yaml
                  subPath: audit-policy-config.yaml
                  readOnly: true
                - name: audit-webhook-config
                  mountPath: /etc/kubernetes/config/audit-webhook-config.yaml
                  subPath: audit-webhook-config.yaml
                  readOnly: true
            volumes:
              - name: audit-policy-config
                configMap:
                  name: audit-policy-config
              - name: audit-webhook-config
                configMap:
                  name: audit-webhook-config
    target:
      group: apps
      version: v1
      kind: Deployment
      name: milo-apiserver
