apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: quota.miloapis.com-recording-rules
  labels:
    app.kubernetes.io/name: milo
    app.kubernetes.io/component: quota-system
    app.kubernetes.io/part-of: milo
    monitoring.coreos.com/prometheus: kube-prometheus
spec:
  groups:
    - name: quota.utilization.5m
      interval: 10s
      rules:
        # Quota utilization ratio (0-1) per consumer and resource type
        # Only calculates ratio when limit > 0 to avoid artificial values
        - record: quota.miloapis.com:utilization:ratio
          expr: |
            milo_quota_bucket_allocated{component="quota_system"}
            /
            (milo_quota_bucket_limit{component="quota_system"} > 0)

        # Quota utilization percentage (0-100) for dashboards
        - record: quota.miloapis.com:utilization:percentage
          expr: quota.miloapis.com:utilization:ratio * 100

        # Available quota ratio (remaining capacity)
        - record: quota.miloapis.com:utilization:available_ratio
          expr: |
            milo_quota_bucket_available{component="quota_system"}
            /
            (milo_quota_bucket_limit{component="quota_system"} > 0)

    - name: quota.system_health.1m
      interval: 15s
      rules:
        # Active resource registrations
        - record: quota.miloapis.com:system:active_registrations
          expr: |
            count by (consumer_kind, resource_type, registration_type) (
              milo_quota_registration_status_condition{component="quota_system", type="Active", status="True"} == 1
            )

        # Failed resource registrations
        - record: quota.miloapis.com:system:failed_registrations
          expr: |
            count by (consumer_kind, resource_type, registration_type) (
              milo_quota_registration_status_condition{component="quota_system", type="ValidationFailed", status="True"} == 1
            )

        # Active grants contributing to quota
        - record: quota.miloapis.com:system:active_grants
          expr: |
            count by (consumer_kind, consumer_name) (
              milo_quota_grant_status_condition{component="quota_system", type="Active", status="True"} == 1
            )

        # Granted claims (successful quota allocations)
        - record: quota.miloapis.com:system:granted_claims
          expr: |
            count by (consumer_kind, consumer_name, triggering_resource_kind) (
              milo_quota_claim_status_condition{component="quota_system", type="Granted", status="True"} == 1
            )

    - name: quota.policies.1m
      interval: 15s
      rules:
        # Ready claim creation policies
        - record: quota.miloapis.com:policy:ready_claim_policies
          expr: |
            count by (target_kind, enabled) (
              milo_quota_claim_policy_status_condition{component="quota_system", type="Ready", status="True"} == 1
            )

        # Ready grant creation policies
        - record: quota.miloapis.com:policy:ready_grant_policies
          expr: |
            count by (trigger_kind, enabled) (
              milo_quota_grant_policy_status_condition{component="quota_system", type="Ready", status="True"} == 1
            )
