apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: milo-apiserver
spec:
  parentRefs:
  - name: default-gateway
    namespace: envoy-gateway-system
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: "/"
      - queryParams:
        - type: Exact
          name: watch
          value: "true"
      timeouts:
        # Allow users to keep watch streams open for a long duration.
        request: 86400s
        backendRequest: 86400s
      backendRefs:
        - group: ""
          kind: Service
          name: milo-apiserver
          port: 6443
      retry: # Retry on 429s so that project storage initialization has time to complete
        codes: [429]
        attempts: 5
        backoff: 300ms
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - group: ""
          kind: Service
          name: milo-apiserver
          port: 6443
      retry: # Retry on 429s so that project storage initialization has time to complete
        codes: [429]
        attempts: 5
        backoff: 300ms
