//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentAcceptance) DeepCopyInto(out *DocumentAcceptance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentAcceptance.
func (in *DocumentAcceptance) DeepCopy() *DocumentAcceptance {
	if in == nil {
		return nil
	}
	out := new(DocumentAcceptance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DocumentAcceptance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentAcceptanceContext) DeepCopyInto(out *DocumentAcceptanceContext) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentAcceptanceContext.
func (in *DocumentAcceptanceContext) DeepCopy() *DocumentAcceptanceContext {
	if in == nil {
		return nil
	}
	out := new(DocumentAcceptanceContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentAcceptanceList) DeepCopyInto(out *DocumentAcceptanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DocumentAcceptance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentAcceptanceList.
func (in *DocumentAcceptanceList) DeepCopy() *DocumentAcceptanceList {
	if in == nil {
		return nil
	}
	out := new(DocumentAcceptanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DocumentAcceptanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentAcceptanceSignature) DeepCopyInto(out *DocumentAcceptanceSignature) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentAcceptanceSignature.
func (in *DocumentAcceptanceSignature) DeepCopy() *DocumentAcceptanceSignature {
	if in == nil {
		return nil
	}
	out := new(DocumentAcceptanceSignature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentAcceptanceSpec) DeepCopyInto(out *DocumentAcceptanceSpec) {
	*out = *in
	out.DocumentRevisionRef = in.DocumentRevisionRef
	out.SubjectRef = in.SubjectRef
	out.AccepterRef = in.AccepterRef
	out.AcceptanceContext = in.AcceptanceContext
	in.Signature.DeepCopyInto(&out.Signature)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentAcceptanceSpec.
func (in *DocumentAcceptanceSpec) DeepCopy() *DocumentAcceptanceSpec {
	if in == nil {
		return nil
	}
	out := new(DocumentAcceptanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocumentAcceptanceStatus) DeepCopyInto(out *DocumentAcceptanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DocumentAcceptanceStatus.
func (in *DocumentAcceptanceStatus) DeepCopy() *DocumentAcceptanceStatus {
	if in == nil {
		return nil
	}
	out := new(DocumentAcceptanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}
