name: cleanup-100-projects
dependencies: []
automanagednamespaces: 0
namespace:
  number: 1
  prefix: test-ayeyzg
  deletestalenamespaces: true
  deleteautomanagednamespaces: true
  enableexistingnamespaces: false
  deletenamespacetimeout: 600000000000
steps:
- phases: []
  measurements:
  - method: APIAvailability
    params:
      action: start
      mode: cluster
      pollFrequency: 1s
      timeout: 10m
    identifier: Avail
    instances: []
  module:
    path: ""
    params: {}
  name: Start system measurements (cleanup)
- phases: []
  measurements:
  - method: Timer
    params:
      action: start
      label: delete-projects
    identifier: PhaseTimer
    instances: []
  module:
    path: ""
    params: {}
  name: Start timer (delete)
- phases:
  - namespacerange: null
    namespacelist: []
    replicaspernamespace: 0
    tuningset: projects-qps
    objectbundle:
    - basename: proj
      objecttemplatepath: ../templates/project.yaml
      templatefillmap:
        labels:
          cl2-group: projects
        ownerName: default-org
      listunknownobjectoptions:
        labelselector:
          matchlabels:
            cl2-group: projects
          matchexpressions: []
  measurements: []
  module:
    path: ""
    params: {}
  name: Delete Projects
- phases: []
  measurements:
  - method: WaitForGenericK8sObjects
    params:
      action: start
      failedConditions: []
      labelSelector: cl2-group=projects
      maxFailedObjectCount: 0
      minDesiredObjectCount: 0
      objectGroup: resourcemanager.miloapis.com
      objectResource: projects
      objectVersion: v1alpha1
      successfulConditions: []
      timeout: 10m
    identifier: WaitNoProjects
    instances: []
  - method: WaitForGenericK8sObjects
    params:
      action: gather
      failedConditions: []
      labelSelector: cl2-group=projects
      maxFailedObjectCount: 0
      minDesiredObjectCount: 0
      objectGroup: resourcemanager.miloapis.com
      objectResource: projects
      objectVersion: v1alpha1
      successfulConditions: []
      timeout: 10m
    identifier: WaitNoProjects
    instances: []
  module:
    path: ""
    params: {}
  name: Wait for Projects deletion
- phases: []
  measurements:
  - method: Timer
    params:
      action: stop
      label: delete-projects
    identifier: PhaseTimer
    instances: []
  module:
    path: ""
    params: {}
  name: Stop timer (delete)
- phases: []
  measurements:
  - method: APIAvailability
    params:
      action: gather
    identifier: Avail
    instances: []
  module:
    path: ""
    params: {}
  name: Gather system measurements (cleanup)
tuningsets:
- name: projects-qps
  initialdelay: 0
  qpsload: null
  randomizedload: null
  steppedload: null
  timelimitedload: null
  randomizedtimelimitedload: null
  parallelismlimitedload: null
  globalqpsload:
    qps: 20
    burst: 20
  poissonload: null
chaosmonkey:
  nodefailure: null
  excludednodes: {}
