name: create-100-projects
dependencies: []
automanagednamespaces: 0
namespace:
  number: 1
  prefix: test-yrgaaj
  deletestalenamespaces: true
  deleteautomanagednamespaces: true
  enableexistingnamespaces: false
  deletenamespacetimeout: 600000000000
steps:
- phases: []
  measurements:
  - method: WaitForGenericK8sObjects
    params:
      action: start
      failedConditions:
      - Terminating=True
      fieldSelector: metadata.name=organizations.resourcemanager.miloapis.com
      maxFailedObjectCount: 0
      minDesiredObjectCount: 1
      objectGroup: apiextensions.k8s.io
      objectResource: customresourcedefinitions
      objectVersion: v1
      successfulConditions:
      - Established=True
      timeout: 5m
    identifier: WaitOrgCRD
    instances: []
  - method: WaitForGenericK8sObjects
    params:
      action: gather
      failedConditions:
      - Terminating=True
      fieldSelector: metadata.name=organizations.resourcemanager.miloapis.com
      maxFailedObjectCount: 0
      minDesiredObjectCount: 1
      objectGroup: apiextensions.k8s.io
      objectResource: customresourcedefinitions
      objectVersion: v1
      successfulConditions:
      - Established=True
      timeout: 5m
    identifier: WaitOrgCRD
    instances: []
  - method: WaitForGenericK8sObjects
    params:
      action: start
      failedConditions:
      - Terminating=True
      fieldSelector: metadata.name=projects.resourcemanager.miloapis.com
      maxFailedObjectCount: 0
      minDesiredObjectCount: 1
      objectGroup: apiextensions.k8s.io
      objectResource: customresourcedefinitions
      objectVersion: v1
      successfulConditions:
      - Established=True
      timeout: 5m
    identifier: WaitProjCRD
    instances: []
  - method: WaitForGenericK8sObjects
    params:
      action: gather
      failedConditions:
      - Terminating=True
      fieldSelector: metadata.name=projects.resourcemanager.miloapis.com
      maxFailedObjectCount: 0
      minDesiredObjectCount: 1
      objectGroup: apiextensions.k8s.io
      objectResource: customresourcedefinitions
      objectVersion: v1
      successfulConditions:
      - Established=True
      timeout: 5m
    identifier: WaitProjCRD
    instances: []
  module:
    path: ""
    params: {}
  name: Preflight ensure CRDs exist
- phases: []
  measurements:
  - method: APIAvailability
    params:
      action: start
      mode: cluster
      pollFrequency: 1s
      timeout: 10m
    identifier: Avail
    instances: []
  - method: ResourceUsageSummary
    params:
      action: start
    identifier: ResUsage
    instances: []
  - method: EtcdMetrics
    params:
      action: start
      masterIPs:
      - etcd.etcd-system.svc.cluster.local:2379
    identifier: Etcd
    instances: []
  module:
    path: ""
    params: {}
  name: Start system measurements
- phases: []
  measurements:
  - method: Timer
    params:
      action: start
      label: create-projects
    identifier: PhaseTimer
    instances: []
  module:
    path: ""
    params: {}
  name: Start timer (create)
- phases:
  - namespacerange: null
    namespacelist: []
    replicaspernamespace: 1
    tuningset: projects-qps
    objectbundle:
    - basename: org
      objecttemplatepath: ../templates/organization.yaml
      templatefillmap:
        name: default-org
        orgType: Standard
      listunknownobjectoptions: null
  measurements: []
  module:
    path: ""
    params: {}
  name: Create default Organization
- phases:
  - namespacerange: null
    namespacelist: []
    replicaspernamespace: 100
    tuningset: projects-qps
    objectbundle:
    - basename: proj
      objecttemplatepath: ../templates/project.yaml
      templatefillmap:
        labels:
          cl2-group: projects
        ownerName: default-org
      listunknownobjectoptions: null
  measurements: []
  module:
    path: ""
    params: {}
  name: Create Projects
- phases: []
  measurements:
  - method: Timer
    params:
      action: stop
      label: create-projects
    identifier: PhaseTimer
    instances: []
  module:
    path: ""
    params: {}
  name: Stop timer (create)
- phases: []
  measurements:
  - method: APIAvailability
    params:
      action: gather
    identifier: Avail
    instances: []
  - method: ResourceUsageSummary
    params:
      action: gather
    identifier: ResUsage
    instances: []
  - method: EtcdMetrics
    params:
      action: gather
      masterIPs:
      - etcd.etcd-system.svc.cluster.local:2379
    identifier: Etcd
    instances: []
  module:
    path: ""
    params: {}
  name: Gather system measurements
tuningsets:
- name: projects-qps
  initialdelay: 0
  qpsload: null
  randomizedload: null
  steppedload: null
  timelimitedload: null
  randomizedtimelimitedload: null
  parallelismlimitedload: null
  globalqpsload:
    qps: 20
    burst: 20
  poissonload: null
chaosmonkey:
  nodefailure: null
  excludednodes: {}
