name: cleanup-100-projects
dependencies: []
automanagednamespaces: 0
namespace:
  number: 1
  prefix: test-9ry8hl
  deletestalenamespaces: true
  deleteautomanagednamespaces: true
  enableexistingnamespaces: false
  deletenamespacetimeout: 600000000000
steps:
- phases: []
  measurements:
  - method: WaitForGenericK8sObjects
    params:
      action: start
      failedConditions:
      - Terminating=True
      fieldSelector: metadata.name=organizations.resourcemanager.miloapis.com
      maxFailedObjectCount: 0
      minDesiredObjectCount: 1
      objectGroup: apiextensions.k8s.io
      objectResource: customresourcedefinitions
      objectVersion: v1
      successfulConditions:
      - Established=True
      timeout: 5m
    identifier: WaitOrgCRD
    instances: []
  - method: WaitForGenericK8sObjects
    params:
      action: gather
      failedConditions:
      - Terminating=True
      fieldSelector: metadata.name=organizations.resourcemanager.miloapis.com
      maxFailedObjectCount: 0
      minDesiredObjectCount: 1
      objectGroup: apiextensions.k8s.io
      objectResource: customresourcedefinitions
      objectVersion: v1
      successfulConditions:
      - Established=True
      timeout: 5m
    identifier: WaitOrgCRD
    instances: []
  - method: WaitForGenericK8sObjects
    params:
      action: start
      failedConditions:
      - Terminating=True
      fieldSelector: metadata.name=projects.resourcemanager.miloapis.com
      maxFailedObjectCount: 0
      minDesiredObjectCount: 1
      objectGroup: apiextensions.k8s.io
      objectResource: customresourcedefinitions
      objectVersion: v1
      successfulConditions:
      - Established=True
      timeout: 5m
    identifier: WaitProjCRD
    instances: []
  - method: WaitForGenericK8sObjects
    params:
      action: gather
      failedConditions:
      - Terminating=True
      fieldSelector: metadata.name=projects.resourcemanager.miloapis.com
      maxFailedObjectCount: 0
      minDesiredObjectCount: 1
      objectGroup: apiextensions.k8s.io
      objectResource: customresourcedefinitions
      objectVersion: v1
      successfulConditions:
      - Established=True
      timeout: 5m
    identifier: WaitProjCRD
    instances: []
  module:
    path: ""
    params: {}
  name: Preflight ensure CRDs exist
- phases: []
  measurements:
  - method: APIAvailabilityMeasurement
    params:
      action: start
      mode: cluster
    identifier: Avail
    instances: []
  - method: ResourceUsageSummary
    params:
      action: start
    identifier: ResUsage
    instances: []
  - method: EtcdMetrics
    params:
      action: start
    identifier: Etcd
    instances: []
  - method: APIResponsivenessPrometheusSimple
    params:
      action: start
    identifier: APISimple
    instances: []
  module:
    path: ""
    params: {}
  name: Start system measurements (cleanup)
- phases: []
  measurements:
  - method: Timer
    params:
      action: start
      label: delete-projects
    identifier: PhaseTimer
    instances: []
  module:
    path: ""
    params: {}
  name: Start timer (delete)
- phases:
  - namespacerange: null
    namespacelist: []
    replicaspernamespace: 0
    tuningset: projects-qps
    objectbundle:
    - basename: proj
      objecttemplatepath: ../templates/project.yaml
      templatefillmap:
        labels:
          cl2-group: projects
        ownerName: default-org
      listunknownobjectoptions:
        labelselector:
          matchlabels:
            cl2-group: projects
          matchexpressions: []
  measurements: []
  module:
    path: ""
    params: {}
  name: Delete Projects
- phases:
  - namespacerange: null
    namespacelist: []
    replicaspernamespace: 0
    tuningset: projects-qps
    objectbundle:
    - basename: org
      objecttemplatepath: ../templates/organization.yaml
      templatefillmap:
        name: default-org
        orgType: Standard
      listunknownobjectoptions:
        labelselector:
          matchlabels:
            cl2-role: owner
          matchexpressions: []
  measurements: []
  module:
    path: ""
    params: {}
  name: Delete Organization
- phases: []
  measurements:
  - method: Timer
    params:
      action: stop
      label: delete-projects
    identifier: PhaseTimer
    instances: []
  module:
    path: ""
    params: {}
  name: Stop timer (delete)
- phases: []
  measurements:
  - method: APIAvailabilityMeasurement
    params:
      action: gather
    identifier: Avail
    instances: []
  - method: ResourceUsageSummary
    params:
      action: gather
    identifier: ResUsage
    instances: []
  - method: EtcdMetrics
    params:
      action: gather
    identifier: Etcd
    instances: []
  - method: APIResponsivenessPrometheusSimple
    params:
      action: gather
    identifier: APISimple
    instances: []
  module:
    path: ""
    params: {}
  name: Gather system measurements (cleanup)
tuningsets:
- name: projects-qps
  initialdelay: 0
  qpsload: null
  randomizedload: null
  steppedload: null
  timelimitedload: null
  randomizedtimelimitedload: null
  parallelismlimitedload: null
  globalqpsload:
    qps: 20
    burst: 20
  poissonload: null
chaosmonkey:
  nodefailure: null
  excludednodes: {}
