apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: identity.miloapis.com-machineaccount
spec:
  serviceRef:
    name: "identity.miloapis.com"
  kind: MachineAccount
  plural: machineaccounts
  singular: machineaccount
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Project
