apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: identity.miloapis.com-machineaccountkey
spec:
  serviceRef:
    name: "identity.miloapis.com"
  kind: MachineAccountKey
  plural: machineaccountkeys
  singular: machineaccountkey
  permissions:
    - list
    - get
    - create
    - update
    - delete
    - patch
    - watch
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Project
