apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Resource Manager service configuration
# Includes telemetry, IAM policies, and other service-specific configurations

components:
  - telemetry
