apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: milo-controller-manager-cluster-admin
subjects:
- kind: ServiceAccount
  name: milo-controller-manager
  namespace: milo-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io