apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: iam-platform-access-approvals-reader
spec:
  launchStage: Beta
  includedPermissions:
    - iam.miloapis.com/platformaccessapprovals.get
    - iam.miloapis.com/platformaccessapprovals.list
    - iam.miloapis.com/platformaccessapprovals.watch
