apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: iam-machine-accounts-viewer
  annotations:
    kubernetes.io/display-name: IAM Machine Accounts Viewer
    kubernetes.io/description: "Allows viewing machine accounts."
spec:
  launchStage: Beta
  includedPermissions:
    - iam.miloapis.com/machineaccounts.get
    - iam.miloapis.com/machineaccounts.list
    - iam.miloapis.com/machineaccounts.watch
