apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: iam-machine-accounts-editor
  annotations:
    kubernetes.io/display-name: IAM Machine Accounts Editor
    kubernetes.io/description: "Allows editing machine accounts."
spec:
  launchStage: Beta
  inheritedRoles:
    - name: iam-machine-accounts-viewer
  includedPermissions:
    - identity.miloapis.com/machineaccounts.create
    - identity.miloapis.com/machineaccounts.update
    - identity.miloapis.com/machineaccounts.patch
    - identity.miloapis.com/machineaccounts.delete
