apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: iam-admin
  annotations:
    kubernetes.io/display-name: IAM Admin
    kubernetes.io/description: "Full access to all IAM resources"
spec:
  launchStage: Beta
  inheritedRoles:
    - name: iam-editor
