apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: identity-machine-account-keys-admin
  annotations:
    kubernetes.io/display-name: Identity Machine Account Keys Admin
    kubernetes.io/description: "Full access to machine account keys."
spec:
  launchStage: Beta
  inheritedRoles:
    - name: identity-machine-account-keys-editor
