apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: identity-machine-account-keys-editor
  annotations:
    kubernetes.io/display-name: Identity Machine Account Keys Editor
    kubernetes.io/description: "Allows editing machine account keys."
spec:
  launchStage: Beta
  inheritedRoles:
    - name: identity-machine-account-keys-viewer
  includedPermissions:
    - identity.miloapis.com/machineaccountkeys.create
    - identity.miloapis.com/machineaccountkeys.update
    - identity.miloapis.com/machineaccountkeys.patch
    - identity.miloapis.com/machineaccountkeys.delete
