apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: owner
spec:
  launchStage: Beta
  inheritedRoles:
    - name: resourcemanager-admin
    - name: core-admin
    - name: apiextensions-reader
