apiVersion: quota.miloapis.com/v1alpha1
kind: ResourceClaim
metadata:
  name: datum-organization-memberships-claim
  namespace: milo-system
spec:
  # Reference to the owner resource specific object instance.
  ownerInstanceRef:
    kind: Organization
    name: datum
  requests:
    # Organization membership count (must reference an active ResourceRegistration)
    - resourceType: "resourcemanager.miloapis.com/OrganizationMembership"
      amount: 1
      dimensions: {}
