apiVersion: quota.miloapis.com/v1alpha1
kind: ResourceClaim
metadata:
  name: datum-cloud-max-httpproxies-claim
  namespace: milo-system
spec:
  # Reference to the owner resource specific object instance.
  ownerInstanceRef:
    kind: Project
    name: datum-cloud
  requests:
    # HTTPProxy entity count (must reference an active ResourceRegistration)
    - resourceType: "networking.datumapis.com/HTTPProxy"
      amount: 1
      dimensions: {}
