apiVersion: quota.miloapis.com/v1alpha1
kind: ResourceGrant
metadata:
  name: datum-max-projects-memberships-grant
  namespace: milo-system

spec:
  # Reference to the owner resource specific object instance.
  ownerInstanceRef:
    apiGroup: resourcemanager.miloapis.com
    kind: Organization
    # Organization name
    name: datum
    uid: "569b6bd5-0965-4d2b-be0e-8157f8cd71ff"
  # Flag to determine if this a default grant or one created in the Staff Portal.
  # Defaults to false.
  isDefault: false
  # List of allowances this grant contains
  allowances:
    # Default number of projects allowed in this organization
    - resourceType: "resourcemanager.miloapis.com/Project"
      buckets:
        - amount: 3
          dimensionSelector: {}