apiVersion: quota.miloapis.com/v1alpha1
kind: ResourceRegistration
metadata:
  name: registration-abc123
spec:
  ownerTypeRef:
    apiGroup: resourcemanager.miloapis.com
    kind: Organization
  # Entity type for countable resources like projects
  type: "Entity"
  # Fully qualified name of the resource type being registered
  resourceType: "resourcemanager.miloapis.com/Project"
  # Description of the quota limit for the resource type
  description: "Maximum number of projects that can be created within an organization."
  # The singular form of the base unit of measurement for the resource
  baseUnit: "Project"
  # The pluralized form of the unit of measurement UI will display to users
  displayUnit: "Projects"
  # Defines how to convert between the base unit and the display unit
  # Formula: baseValue / unitConversionFactor = displayValue
  unitConversionFactor: 1
  # Dimensions that can be used in ResourceGrant selectors
  # No dimensions as this is just a very simple entity-based use case
  dimensions: [] 