kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: "iam.miloapis.com"
        kind: "UserPreference"
        version: "v1alpha1"
      metricNamePrefix: milo_user_preferences
      commonLabels:
        component: iam
        resource_type: user_preference
      labelsFromPath:
        user_name: [spec, userRef, name]
      metrics:
        - name: "info"
          help: "Information about user preferences"
          each:
            type: Info
            info:
              labelsFromPath:
                uid: [metadata, uid]
                name: [metadata, name]
                namespace: [metadata, namespace]

        - name: "status_condition"
          help: "Status conditions for user preferences"
          each:
            type: Info
            info:
              path: [status, conditions]
              labelsFromPath:
                type: [type]
                status: [status]

        - name: "created_timestamp"
          help: "Timestamp when the user preference was created"
          each:
            type: Gauge
            gauge:
              path: [metadata, creationTimestamp]

        - name: "current_generation"
          help: "The current generation for the user preference"
          each:
            type: Gauge
            gauge:
              path: [metadata, generation]
